#cmakedefine HAVE_ARC4RANDOM 1
#cmakedefine HAVE_DEVPOLL   1
#cmakedefine HAVE_EPOLL_CTL 1
#cmakedefine HAVE_GETRUSAGE   1
#cmakedefine HAVE_GETTIMEOFDAY 1
#cmakedefine HAVE_GMTIME_R 1
#cmakedefine HAVE_GNUTLS 1
#cmakedefine HAVE_KEVENT 1
#cmakedefine HAVE_MMAP 1
#cmakedefine HAVE_NANOSLEEP 1
#cmakedefine HAVE_OPENSSL 1
#cmakedefine HAVE_POLL 1
#cmakedefine HAVE_PORT_CREATE 1
#cmakedefine HAVE_POSIX_SPAWN 1
#cmakedefine HAVE_SELECT 1
#cmakedefine HAVE_SENDMSG   1
#cmakedefine HAVE_SIGNALFD   1
#cmakedefine HAVE_SOCKETPAIR 1
#cmakedefine HAVE_STRLCAT 1
#cmakedefine HAVE_STRLCPY 1
#cmakedefine HAVE_STRNLEN 1
#cmakedefine HAVE_STRTOK_R 1
#cmakedefine HAVE_WRITEV 1
#cmakedefine HAVE_PORT_H 1
#cmakedefine HAVE_SPAWN_H 1
#cmakedefine HAVE_SYS_DEVPOLL_H 1
#cmakedefine HAVE_SYS_EVENT_H 1
#cmakedefine HAVE_SYS_POLL_H 1
#cmakedefine HAVE_SYS_SELECT_H 1
#cmakedefine HAVE_SYS_SIGNALFD_H 1
#cmakedefine HAVE_SYS_UIO_H 1
